import {ChatEngine, ChatFeed} from 'react-chat-engine';
import './App.css';
import Chatfeed from './ChatFeed.jsx';
import LoginForm from './LoginForm';
const App = () =>{
    if(!localStorage.getItem('username')) return <LoginForm/>

    return(
        <ChatEngine
            height = "100vh"
            projectID = "6960c5db-a87b-4ea2-99b1-c995dbd94ef5" //generated by chatengine.io 
            userName = {localStorage.getItem('username')}
            userSecret = {localStorage.getItem('password')}
            renderChatFeed={(chatAppProps) => <Chatfeed {...chatAppProps} />}  //spreads the props given by chat engine
        />
    )
}

export default App;